Feature/dr 2925/fallback for featured item
NYPL/digital-collections pull request #131
Opened 2024-05-02 19:15 UTC by avertrees

## Ticket:

- JIRA ticket [DR-2925](https://jira.nypl.org/browse/DR-2925)

## This PR does the following:

- updates hero component to use a fallback image for the featured item

## How has this been tested?

¯\_(ツ)_/¯ 

## Accessibility concerns or updates

-

### Checklist:

- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

2024-05-02 19:17 UTC, avertrees commented on src/types/FeaturedItemData.ts
I was optimistic in trying to use types for the first time but then I got confused and gave up

2024-05-02 21:26 UTC, EdwinGuzman requested changes
The changes I am requesting are mostly for cleanup and to add the typescript interface. Otherwise, this works as intended so this is great!

One way I tested this is by adding `responseData.featuredItem.foregroundImageSrc = "foo.jpg";` in the `useEffect`:

```
const fetchData = async () => {
      const response = await fetch(`/api/featuredItem`);
      const responseData = await response.json();
      responseData.featuredItem.foregroundImageSrc = "foo.jpg";
      setData(responseData);
    };
```

This makes it so that "foo.jpg" will not load and the fallback image and text will load.

2024-05-02 21:26 UTC, EdwinGuzman commented on src/data/defaultFeaturedItemData.ts
> +      imageSrc: "/482815.jpg",
You don't seem to be using the `imageSrc` property anywhere.

2024-05-02 21:26 UTC, EdwinGuzman commented on src/data/defaultFeaturedItemData.ts
> +const defaultFeaturedItem: any = {
Here is a case where you can use the `FeaturedItemData` interface.

If you had a single object, you can type it as the following as an example:

```
const development: FeaturedItemData = {
  featuredItem: {
    imageID: "482815",
    backgroundImageSrc: "/482815.jpg",
    foregroundImageSrc: "/482815.jpg",
    uuid: "510d47d9-4f93-a3d9-e040-e00a18064a99",
    title: "Watuppa, From water front, Brooklyn",
    href: "https://qa-digitalcollections.nypl.org/items/510d47d9-4f93-a3d9-e040-e00a18064a99",
  },
  numberOfDigitizedItems: "875,861",
};
```

To be clear, DON'T change your data structure, it's fine but it needs an additional typescript utility type to help define the entire structure. What you can use is the `Record` utility type to help https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type

I'll leave the rest for you to work through but let me know if you run into issues.

2024-05-02 21:26 UTC, EdwinGuzman commented on src/components/hero/campaignHero.tsx
>    const [data, setData] = useState<any>({});
Here is another place where the `any` can be replaced with the `FeaturedItemData` interface.

2024-05-02 22:38 UTC, avertrees commented on src/components/hero/campaignHero.tsx
> +    defaultFeaturedItem[appConfig["environment"]];
yes

2024-05-02 22:38 UTC, avertrees commented on src/utils/utils.ts
> +  const fallbackCount = defaultFeaturedItems[appConfig.environment];
OOP good catch

2024-05-02 22:55 UTC, avertrees commented on src/components/hero/campaignHero.tsx
> +  );
oop I forgot to remove that line before pushing.

2024-05-03 13:51 UTC, EdwinGuzman commented on src/components/hero/campaignHero.tsx
> +    console.log("data is:", data);
Nitpick: in the DS we add a prefix to know where the error is coming from. You can still see this in the stack trace but it's helpful if you just read the console message. So something like, "CampaignHero: the data is ...".

2024-05-03 13:52 UTC, EdwinGuzman commented on src/components/hero/campaignHero.tsx
> +        fallbackSrc: data.featuredItem.foregroundImageSrc,
Not necessary to have this anymore but it doesn't hurt to include.

2024-05-03 13:52 UTC, EdwinGuzman approved these changes
Some minor comments but works well.

2024-05-03 14:01 UTC, 7emansell approved these changes
Lgtm except as we talked about, I'd like to find a way to test this. I would expect something like this to work: 

```
it("renders the fallback image", async () => {
    (global as any).fetch = jest.fn(() =>
      Promise.reject(new Error("fails to fetch"))
    ) as jest.Mock;
    render(<CampaignHero imageID="5273165" />);
    await waitFor(() => {
      expect(
        screen.getByText("Watuppa, From water front, Brooklyn")
      ).toBeInTheDocument();
    });
  });
``` 
but it fails.

2024-05-03 14:06 UTC, EdwinGuzman commented
Very true, I forgot about testing 😓 

Try `fireEvent.error` to trigger the `onerror` event and then check if the image has the fallback url. https://stackoverflow.com/questions/44462665/how-do-you-use-jest-to-test-img-onerror

2024-05-10 18:14 UTC, merged