remove query params from redirects of phase 3 pages
NYPL/digital-collections pull request #173
Opened 2024-07-31 15:39 UTC by avertrees

## Ticket:

- JIRA ticket https://newyorkpubliclibrary.atlassian.net/browse/DR-3028

## This PR does the following:

- removes the query params from the redirect of the phase 3 pages, it's a bit redundant as it's another layer of conditional redirection on top of the middleware file.

## How has this been tested?

Locally. Can change the APP_ENV back to qa in vercel to test if we need.

## Accessibility concerns or updates

-

### Checklist:

- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.
- [ ] I have updated the CHANGELOG.md.

2024-07-31 16:09 UTC, 7emansell requested changes
I'm still seeing what Bridgette pointed out [here](https://newyorkpubliclibrary.atlassian.net/browse/DR-3028?focusedCommentId=114784) (ex., http://localhost:3000/collections/women-of-distinction-remarkable-in-works-and-invincible-in-character#/?tab=about redirects to http://localhost:3000/#/?tab=about, not http://localhost:3000/). 
I just tried a bunch of stuff, including directly setting the `window.location` and none of it worked to remove the hash, sending me down this path: https://stackoverflow.com/questions/72306039/nextjs-router-redirect-hash-routes-to-non-hash-routes . The `router.replace` you're using in `/search/results` is not what it's hitting, it's hitting the serverside middleware, so that's where the change needs to be made, but the hash is only available clientside so it's gnarly . I'll keep digging!!

2024-07-31 16:51 UTC, avertrees commented
@7emansell did you change the APP_ENV to 'qa' locally?

2024-07-31 18:37 UTC, EdwinGuzman commented
It's fine to move on without this for now. We'll chat more about this later.

2024-08-01 14:31 UTC, EdwinGuzman commented
@7emansell , we tried a couple of things and maybe the update is not the most ideal but it works and will eventually be removed when this page is released.
The point about `#/?...` not being removed was indeed gnarly. I think this is, or was, a ruby of rails routing convention for hashes. I know it was definitely something I struggled with in the Angular days.

Talking to Ali, _if_ the feature that created the `#/?...` hashes needs to be implemented in DCF, I will argue against keeping this convention since it's not commonly used. So at that point it won't be a one-to-one feature parity.

2024-08-01 14:32 UTC, EdwinGuzman approved these changes
Can you just add a comment in `homePage.tsx` above the router call to explain why it's there? And also a note about removing that code later in phase 3.

2024-08-01 14:47 UTC, 7emansell approved these changes

2024-08-01 15:19 UTC, merged