DR-3061/tag new pages with aa
NYPL/digital-collections pull request #191
Opened 2024-08-30 18:58 UTC by avertrees

## Ticket:

- JIRA ticket [ tag new DCF pages with Adobe Analytics](https://newyorkpubliclibrary.atlassian.net/browse/DR-3061)

## This PR does the following:

- tags all pages with Adobe Analytics (I left collections/[:uuid] to just pass the url parameter into AA, regardless if it's a uuid or a slug)
- 
## How has this been tested?

locally with debugger

## Accessibility concerns or updates

-

### Checklist:

- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.
- [ ] I have updated the CHANGELOG.md.

2024-08-30 20:22 UTC, EdwinGuzman requested changes
Looks good just a minor change for one page name value.

The following is not relevant to the AA update in this PR but it's very apparent from reviewing this:
I just noticed there are two patterns for rendering a page component, and therefore where `PageLayout` is rendered. Either it's in the App Router `page.tsx` file or in a specific `[x]Page.tsx` file. Either is fine but I recommend you and @7emansell  pick one for consistency. It does not need to be part of this PR.

2024-08-30 20:22 UTC, EdwinGuzman commented on app/src/components/pageLayout/pageLayout.tsx
> -    const route = pathname || "";
I don't think the above comment is relevant anymore.

2024-08-30 20:22 UTC, EdwinGuzman commented on app/collections/lane/[slug]/page.tsx
> +  const pageName = `dc|collections|lane|${params.slug}`;
Remove `dc|` from here. The prefix is added automatically in the `trackVirtualPageView` function when it gets sent to Adobe.

2024-09-03 14:13 UTC, EdwinGuzman approved these changes
The AA chrome extension works but I don't think it picks up virtual views. Is this something you would normally test in the QA env or in the AA dashboard? (AA is picked up in Vercel for the entities dev account)

2024-09-03 14:22 UTC, avertrees commented
> The AA chrome extension works but I don't think it picks up virtual views. Is this something you would normally test in the QA env or in the AA dashboard? (AA is picked up in Vercel for the entities dev account)

@EdwinGuzman yes, Lana or Bridgette would check the QA dashboard. It takes a little while for the data to send to the dashboard too.

When you say AA is picked up in Vercel in the entities dev account, do you mean that you're seeing the page names for these pages in the NYPL entities dev account when you preview them in Vercel?

2024-09-03 15:16 UTC, EdwinGuzman commented
Yeah, I see the suite is picked up in the chrome extension and in the dashboard I see:
<img width="261" alt="Screenshot 2024-09-03 at 11 14 58 AM" src="https://github.com/user-attachments/assets/6b767c45-b04b-474b-b94f-d4d59947a12e">

So it's working. You can see some issues like `dc|dc|collections|lane|photographs` but that has been fixed and also the new pages like `dc|search-results`, `dc|all-collections`, etc.

2024-09-03 15:26 UTC, avertrees commented
@EdwinGuzman cool, yeah I think this is enough for now. I'll merge this in so Lana and Bridgette can review.

2024-09-03 15:26 UTC, merged